### ISSUE TITLE
1.20.6 Build Request

### ISSUE THREAD

**Issue by R0NAM1** [Tanguygab/CCTV#4]
I'm currently running a 1.20.6 world I cannot downgrade because the backups were way to old, and I'm not updating anytime soon. This plugin looks amazing and I want to add it to my server so me and my friends can screw around, but no build exists for 1.20.6.

From what I can tell looking at the source code, it's just changing the build dependency and that should be it nay a few API changes. I attempted this but I was not able to build it, partially because I'm not sure how to compile it properly, it kept complaining:

```
 Where:
Build file '/home/r0nam1/Coding/CCTV/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'CCTV'.
> Could not find method java() for arguments [build_3mrdjffp7vk0p7pp96031ci1u$_run_closure1@172ab83a] on root project 'CCTV' of type org.gradle.api.Project

```

On a raw git clone, no modifications.

Thanks!

**Comment by Tanguygab** [comment]
no idea what the error is but here's a jar for 1.21 which should work on 1.20.6 as well
https://cdn.discordapp.com/attachments/643555650135130123/1259495435534340096/CCTV-9.0.3.jar?ex=66951e88&is=6693cd08&hm=0d48f96a15659f1c634ae23e37fcd9adfdf441274f0c34d0e6c7a7e5226b5641&
if you can't download it, it's also on the Discord server in the #support channel

**Comment by R0NAM1** [comment]
So far that seems to have worked! When do you plan on releasing it on the Spigot Page?

**Comment by Tanguygab** [comment]
apparently AddNosje just did! https://www.spigotmc.org/resources/security-camera-plugin-cctv-1-12-2-1-21.60310/updates
